kind: Namespace
apiVersion: v1
metadata:
  name: helloworld
  labels:
    name: helloworld

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-pod
  namespace: helloworld
spec:
  selector:
    matchLabels:
      run: hello-pod
  replicas: 2
  template:
    metadata:
      labels:
        run: hello-pod
    spec:
      containers:
      - name: hello-pod
        image: nginx:1.21.6
        ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: helloworld
  name: hello-service
  labels:
    run: hello-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: hello-pod
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  namespace: helloworld
  name: hello-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello.internal
    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: hello-service
            port:
              number: 80









